
version: "3.8"
services:
  backend:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - movie-rental-db

  movie-rental-db:
    image: "mysql:8.0.30"
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: movierental
      MYSQL_USER: test
      MYSQL_PASSWORD: test123
      MYSQL_ROOT_PASSWORD: admin123

