
version: "3.8"
services:
  movie-rental-db:
    image: "mysql:8.0.30"
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: movierental
      MYSQL_USER: test
      MYSQL_PASSWORD: test123
      MYSQL_ROOT_PASSWORD: test123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./movie-rental-1.0-SNAPSHOT.jar:/app/movie-rental-1.0-SNAPSHOT.jar
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - movie-rental-db